kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-volume
  labels:
    type: local
  namespace: kubeflow
  annotations:
    pv.beta.kubernetes.io/gid: "1000"  
    pv.beta.kubernetes.io/uid: "1000"
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-claim
  namespace: kubeflow
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
